### ISSUE TITLE
[11.0] pos_lot_selection, wrong quantity in stock delivery order when selling multiple lots

### ISSUE THREAD

**Issue by carloselinge** [OCA/pos#318] opened 2019-01-03 21:19 UTC
Hello, I just found the following problem at the point of sale for the odoo 11 enterprise:

At the point of sale I buy three of a lot and then in the same transaction I buy two products from another lot, these lots are of the same product.

![1](https://user-images.githubusercontent.com/29591038/50661565-21872b00-0f69-11e9-802f-3a893ea703de.png)

![2](https://user-images.githubusercontent.com/29591038/50661658-6743f380-0f69-11e9-8df4-b098034a1cd9.png)

![3](https://user-images.githubusercontent.com/29591038/50661700-83479500-0f69-11e9-9c3c-97d60e299c98.png)

The purchase is donde and when we review the movement in the sales order area we realize that the movement says it is correct

![cantidad](https://user-images.githubusercontent.com/29591038/50661744-a6724480-0f69-11e9-93f3-89a4e9593aca.png)

however when reviewing the movement in the inventory we realize that it was modified in 5 in each of the lots, which means that the inventory does not match the sales

![mal](https://user-images.githubusercontent.com/29591038/50661785-d15c9880-0f69-11e9-8552-d359d64ed766.png)

**Comment by hydrosIII** [comment] 2019-01-03 21:37
I confirm this issue, as it is also happening for me in the Enterprise version

**Comment by legalsylvain** [comment] 2019-01-04 01:29
Hi. Did you reproduced the bug in the community Edition ?

**Comment by hydrosIII** [comment] 2019-01-04 04:46
Confirmed, reproduced in runbot odoo 11: http://3349927-11-0-e90b26.runbot2.odoo-community.org/web?#id=18&view_type=form&model=stock.picking using the runbot from OCA in the pos branch, Here are the screenshots.

The POS interface:

![captura de pantalla de 2019-01-03 22-37-33](https://user-images.githubusercontent.com/7807363/50674124-ef95b900-0fa8-11e9-9c05-8637c79a905e.png)
![captura de pantalla de 2019-01-03 22-37-40](https://user-images.githubusercontent.com/7807363/50674125-f15f7c80-0fa8-11e9-8445-194d088238ef.png)
![captura de pantalla de 2019-01-03 22-37-51](https://user-images.githubusercontent.com/7807363/50674128-f290a980-0fa8-11e9-986e-f148be18b0ef.png)

![captura de pantalla de 2019-01-03 22-37-55](https://user-images.githubusercontent.com/7807363/50674091-b6f5
The order created:

![captura de pantalla de 2019-01-03 22-39-01](https://user-images.githubusercontent.com/7807363/50674107-cffe9080-0fa8-11e9-83f7-0cc51de1ae6b.png)
df80-0fa8-11e9-98c9-fcd22d37afa2.png)

The stock move:
![captura de pantalla de 2019-01-03 22-39-17](https://user-images.githubusercontent.com/7807363/50674095-b8bfa300-0fa8-11e9-9d51-b1a1851ceb4e.png)

**Comment by pedrobaeza** [comment] 2019-01-04 08:59
But why is this published here if it's something about standard odoo?

**Comment by hydrosIII** [comment] 2019-01-05 01:01
I dont understand, can you clarify your question?  It is (I think) a bug in odoo_lot_selection addon, as per the evidence submitted. Is this not the place to report this? Where is it then?

**Comment by pedrobaeza** [comment] 2019-01-05 11:34
There's no odoo_lot_selection module in this repository.

**Comment by carloselinge** [comment] 2019-01-05 16:47
Sorry for the name, the add-on is called pos_lot_selection and if it is part of this repository and the bug does not occur at the odoo enterprise or community point of sale until this add-on is installed

**Comment by pedrobaeza** [comment] 2019-01-05 16:49
I'm not sure the problem is related to the module, but @chienandalu can tell us

**Comment by carloselinge** [comment] 2019-01-05 16:58
thank you very much, we are really interested in knowing what the problem is or where it is, because until now it looked very promising

**Comment by chienandalu** [comment] 2019-01-07 09:45
I've tested it in an Odoo 11.0 runbot and the same bug exists. It duplicates lot qtys. If you were so kind to open this same issue there (https://github.com/odoo/odoo/issues)

**Comment by hydrosIII** [comment] 2019-01-07 20:45
Sorry just to check, @chienandalu , it duplicates lot qtys without the module, just with the plain lot selection in point of sale?

**Comment by carloselinge** [comment] 2019-01-08 00:04
Terrible truth when the problem is inherent in the program, thank you very much for the support, I will put the issue there to see how it goes and in case of that is resolved I hope you do not mind being notified with another post, thank you again for the prompt reply

**Comment by chienandalu** [comment] 2019-01-08 07:00
That's it @hydrosIII

**Comment by chienandalu** [comment] 2019-01-08 07:00
We can close this, @pedrobaeza

**Closed as completed** 2019-01-08 07:03 UTC

**Comment by carloselinge** [comment] 2019-01-08 11:06
https://github.com/odoo/odoo/issues/30006#issuecomment-452249181

And here the answer
