### ISSUE TITLE
[8.0] use of related field in rule

### ISSUE THREAD

**Issue by cubells** [OCA/pos#112] opened 2016-08-04 06:55 UTC
Is It possible to use a related field for a rule?

I've got an error:
`ValueError: Invalid field 'company_id' in leaf "<osv.ExtendedLeaf: ('company_id', '=', False) on account_fiscal_position_tax (ctx: )>"`
due to this line:
https://github.com/OCA/pos/blob/8.0/pos_pricelist/security/account_fiscal_position_security.xml#L9

Is it necessary store=True here?:
https://github.com/OCA/pos/blob/8.0/pos_pricelist/models/account_fiscal_position.py#L11

**Comment by pedrobaeza** [comment] 2016-08-04 07:08
I haven't experimented any problem with that (I was the original author of it in https://github.com/OCA/pos/pull/85)

**Comment by cubells** [comment] 2016-08-04 07:14
Error raised after update all code from server and try to do a sale order. I'll test again.

**Comment by legalsylvain** [comment] 2016-09-21 17:56
hi @cubells, is this bug confirmed ?

**Comment by cubells** [comment] 2016-09-30 14:27
@legalsylvain : Yes, It is.

Tested and retested. If related field is not defined as store=True, then it can't be searched.

And then, this rule:
https://github.com/OCA/pos/blob/8.0/pos_pricelist/security/account_fiscal_position_security.xml#L9

throw a 

`ValueError: Invalid field 'company_id' in leaf "<osv.ExtendedLeaf: ('company_id', '=', False) on account_fiscal_position_tax (ctx: )>"`

Solution is this put store=True in this line:
https://github.com/OCA/pos/blob/8.0/pos_pricelist/models/account_fiscal_position.py#L11

Thanks.

**Comment by StefanRijnhart** [comment] 2017-12-07 19:20
@cubells How did you test this? I could not reproduce it. See my comment on Sylvain's fix, #229

**Comment by legalsylvain** [comment] 2018-01-05 22:31
Hi @cubells. I just retested this bug and did not reproduced it.
(Installed Odoo (OCB) + pos_pricelist) and try to access to the model account_fiscal_position_tax with the demo user. 

Maybe do you use an old version of Odoo or there is a problem on your instance. 
If the bug persist, could you point more precisely. (for exemple, with a demo on an instance on runbot, or writing a test in pos_pricelist) ?

Closing in the meantime. Feel free to reopen if you have new elements.

regards.

**Closed as completed by legalsylvain** 2018-01-05 22:31 UTC
