### ISSUE TITLE
Full switch to last copier template

### ISSUE THREAD

**Issue by legalsylvain** [OCA/pos#906] opened 2022-12-05 16:01 UTC
Hi all,

with https://github.com/OCA/pos/pull/905, https://github.com/OCA/pos/pull/904, https://github.com/OCA/pos/pull/900, https://github.com/OCA/pos/pull/901, https://github.com/OCA/pos/pull/902, https://github.com/OCA/pos/pull/903, https://github.com/OCA/pos/pull/896
- i updated all the branches from 12.0 16.0 to the latest copier template, fixing various issues
- I switched from Travis to github action for the release 10 & 11.

If you have pending PR, you can rebase it and it could fixes some test / pre-commit errors.

Except for old versions (7, 8, 9) for which no copier template exist, all is migrated to github actions. 

Kind regards.

CC : @OCA/pos-maintainers, @sbidoul

**Comment by ivantodorovich** [comment] 2022-12-19 18:30
Thanks a lot ❤️ 

I'm closing this as the issue is considered solved

**Closed as completed by ivantodorovich** 2022-12-19 18:30 UTC
Labels: bug
