### ISSUE TITLE
Error at session load

### ISSUE THREAD

**Issue by debaetsr** [OCA/pos#60] opened 2015-10-22 13:46 UTC
module: pos_pricelist
version: 8.0  (downloaded from apps.odoo.com)

**Steps to reproduce**
Open new session

**Current behavior**
Loading product.product
TypeError: this.compute_all is not a function
    at module.Orderline.module.Orderline.extend.get_all_prices (http://testsite.myfqdn.be/web/js/web.assets_backend/de8ad41:4632:239)
    at module.PosDB.module.PosDB.extend.add_products (http://testsite.myfqdn.be/web/js/web.assets_backend/de8ad41:4620:345)
    at prototype.(anonymous function) [as add_products](http://testsite.myfqdn.be/web/js/web.assets_common/ece4115:1089:595)
    at Object.module.PosModel.Backbone.Model.extend.models.loaded (http://testsite.myfqdn.be/web/js/web.assets_backend/de8ad41:4388:3668)
    at Object.<anonymous> (http://testsite.myfqdn.be/web/js/web.assets_backend/de8ad41:4393:48)
    at Object.<anonymous> (http://testsite.myfqdn.be/web/js/web.assets_common/ece4115:249:688)
    at fire (http://testsite.myfqdn.be/web/js/web.assets_common/ece4115:243:299)
    at Object.self.fireWith [as resolveWith](http://testsite.myfqdn.be/web/js/web.assets_common/ece4115:248:198)
    at Object.<anonymous> (http://testsite.myfqdn.be/web/js/web.assets_common/ece4115:249:879)
    at fire (http://testsite.myfqdn.be/web/js/web.assets_common/ece4115:243:299)
Ok

**Expected behavior**
Working POS

**Comment by SergioViteri** [comment] 2015-10-26 11:43
Same problem here

**Comment by AdilHoumadi** [comment] 2015-10-26 16:06
Hello,

Can someone post further informations related this error. (modules installed, JS output in the debug mode) ...

Thanks.

**Comment by SergioViteri** [comment] 2015-10-26 16:23
Hi,

This is the list of installed modules: https://www.dropbox.com/s/ocsh82x794mif7u/ir.module.module.xlsx?dl=0

and this is the output is: 
pos_pricelist_models/module.Orderline<.get_all_prices@http://odoo.zacatrus.es/web/js/web.assets_backend/4602669:4551:234 pos_pricelist_db/module.PosDB<.add_products@http://odoo.zacatrus.es/web/js/web.assets_backend/4602669:4539:335 declare/</openerp.Class.extend/</prototype[name]</<@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:1089:592 openerp_pos_models/module.PosModel<.models<.loaded@http://odoo.zacatrus.es/web/js/web.assets_backend/4602669:4307:3660 load_model/<@http://odoo.zacatrus.es/web/js/web.assets_backend/4602669:4312:42 .Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:249:685 jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:243:281 jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:248:198 .Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:249:856 jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:243:281 jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:248:198 jQuery.Callbacks/self.fire@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:249:31 jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:243:281 jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:248:198 .Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:249:856 jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:243:281 jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:248:198 .Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:249:856 jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:243:281 jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:248:198 done@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:682:86 .send/callback@http://odoo.zacatrus.es/web/js/web.assets_common/d535558:735:15

Thank you,
Sergio.

**Comment by AdilHoumadi** [comment] 2015-10-26 16:40
The output still minified.
Please add this param to your URL while accessing to point of sale : `debug`
the url should be like this : `http://localhost:8069/pos/web/?debug#action=pos.ui`

Thanks.

**Comment by SergioViteri** [comment] 2015-10-26 16:52
mmm, same response with that url (see attach). Is there a log file or something I can check?

![captura de pantalla de 2015-10-26 17 51 09](https://cloud.githubusercontent.com/assets/215385/10735853/4fdc3c34-7c0a-11e5-84e0-433cb0073ac4.png)

**Comment by legalsylvain** [comment] 2015-10-26 17:17
@SergioViteri : 
- could you add a file with all your modules installed. some lines seems missing. (in your file in dropbox)
- could you set 'name' / 'author' 'state' columns in your extract ?

regards.

**Comment by SergioViteri** [comment] 2015-10-26 17:25
I think everything is here: https://www.dropbox.com/s/4vwutai4b5dsn3z/ir.module.module-1.csv?dl=0

bests.

**Comment by AdilHoumadi** [comment] 2015-10-26 18:04
@SergioViteri, Yeah, the last output in the image is better !! There, we can see exactly which line cause problems. Please update your issue with that one ?

Thanks

**Comment by SergioViteri** [comment] 2015-10-26 18:55
Here we go:

pos_pricelist_models/module.Orderline<.get_all_prices@http://odoo.zacatrus.es/pos_pricelist/static/src/js/models.js:193:31
pos_pricelist_db/module.PosDB<.add_products@http://odoo.zacatrus.es/pos_pricelist/static/src/js/db.js:175:34
declare/</openerp.Class.extend/</prototype[name]</<@http://odoo.zacatrus.es/web/static/src/js/openerpframework.js:126:39
openerp_pos_models/module.PosModel<.models<.loaded@http://odoo.zacatrus.es/point_of_sale/static/src/js/models.js:282:17
load_model/<@http://odoo.zacatrus.es/point_of_sale/static/src/js/models.js:401:44
.Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1129:88
jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:974:38
jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1084:49
.Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1136:81
jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:974:38
jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1084:49
jQuery.Callbacks/self.fire@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1091:33
jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:974:38
jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1084:49
.Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1136:81
jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:974:38
jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1084:49
.Deferred/promise.then/</</<@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1136:81
jQuery.Callbacks/fire@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:974:38
jQuery.Callbacks/self.fireWith@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:1084:49
done@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:7803:33
.send/callback@http://odoo.zacatrus.es/web/static/lib/jquery/jquery.js:8518:57

**Comment by AdilHoumadi** [comment] 2015-10-26 21:16
I Still need a way to reproduce this bug.
With a fresh DB I install pos_pricelist with the Spanish Localization, and I successfully start the point of sale.
Can you describe exactly what you did ?

Thanks

```
select name, author, state from ir_module_module where state = 'installed' order by name;

         name         |                        author                         |   state   
----------------------+-------------------------------------------------------+-----------
 account              | OpenERP SA                                            | installed
 account_voucher      | OpenERP SA                                            | installed
 analytic             | OpenERP SA                                            | installed
 auth_crypt           | ['OpenERP SA', 'FS3']                                 | installed
 auth_signup          | OpenERP SA                                            | installed
 base                 | OpenERP SA                                            | installed
 base_iban            | OpenERP SA                                            | installed
 base_import          | OpenERP SA                                            | installed
 base_setup           | OpenERP SA                                            | installed
 base_vat             | OpenERP SA                                            | installed
 board                | OpenERP SA                                            | installed
 bus                  | OpenERP SA                                            | installed
 decimal_precision    | OpenERP SA                                            | installed
 edi                  | OpenERP SA                                            | installed
 email_template       | OpenERP SA                                            | installed
 fetchmail            | OpenERP SA                                            | installed
 im_chat              | OpenERP SA                                            | installed
 im_odoo_support      | OpenERP SA                                            | installed
 l10n_es              | Spanish Localization Team                             | installed
 mail                 | OpenERP SA                                            | installed
 payment              | OpenERP SA                                            | installed
 payment_transfer     | OpenERP SA                                            | installed
 point_of_sale        | OpenERP SA                                            | installed
 portal               | OpenERP SA                                            | installed
 portal_sale          | OpenERP SA                                            | installed
 portal_stock         | OpenERP SA                                            | installed
 pos_pricelist        | Adil Houmadi @Taktik,Odoo Community Association (OCA) | installed
 procurement          | OpenERP SA                                            | installed
 product              | OpenERP SA                                            | installed
 report               | OpenERP SA                                            | installed
 sale                 | OpenERP SA                                            | installed
 sales_team           | OpenERP SA                                            | installed
 sale_stock           | OpenERP SA                                            | installed
 share                | OpenERP SA                                            | installed
 stock                | OpenERP SA                                            | installed
 stock_account        | OpenERP SA                                            | installed
 web                  |                                                       | installed
 web_calendar         | OpenERP SA, Valentino Lab (Kalysto)                   | installed
 web_diagram          |                                                       | installed
 web_gantt            |                                                       | installed
 web_graph            |                                                       | installed
 web_kanban           |                                                       | installed
 web_kanban_gauge     |                                                       | installed
 web_kanban_sparkline |                                                       | installed
 web_tests            |                                                       | installed
 web_view_editor      |                                                       | installed
```

**Comment by SergioViteri** [comment] 2015-10-27 07:30
Actually, we have been using Odoo much time with much data. What is new for us is pos and pos_pricelist. I can try to reproduce the error with a fresh database if it helps.

**Comment by SergioViteri** [comment] 2015-10-27 08:07
With a fresh copy works just fine. Maybe we can leave a log or mark to know which product/element causes the issue...

**Comment by AdilHoumadi** [comment] 2015-10-27 08:25
@SergioViteri, Thanks for your feedback.

**Comment by SergioViteri** [comment] 2015-10-27 10:30
@AdilHoumadi Do you think you can fix it to work with our database?

**Comment by debaetsr** [comment] 2015-10-27 10:32
It seems my module point_of_sales isn't the latest revision, missing the function compute_all. I'll try to update and let you know

**Comment by SergioViteri** [comment] 2015-10-27 10:56
great :) Thank you!

**Comment by debaetsr** [comment] 2015-10-27 11:43
going to latest revision of odoo/8.0 fixes the problem.

Regards,
Ruben

**Comment by SergioViteri** [comment] 2015-10-27 13:48
@debaetsr Not for me :-(

**Comment by debaetsr** [comment] 2015-10-27 14:49
Can you verify if file
   point_of_sale/static/src/js/models.js
contains:

 get_tax_details: function(){
            return this.get_all_prices().taxDetails;
        },
compute_all: function(taxes, price_unit) {
            var self = this;
            var res = [];
            var currency_rounding = this.pos.currency.rounding;

around line 861?

Missing this function throws the execption.

**Comment by SergioViteri** [comment] 2015-10-27 14:57
Yes, it contains this lines. This is my models.js: https://www.dropbox.com/s/gc5vclzahm03obu/models.js?dl=0

**Comment by AdilHoumadi** [comment] 2015-10-27 15:52
@SergioViteri, If possible to give the  commit number of your Odoo code ?

**Comment by SergioViteri** [comment] 2015-10-27 16:05
@AdilHoumadi  I just download de nightly version of today and still happens: odoo_8.0.20151027_all.deb

**Comment by AdilHoumadi** [comment] 2015-10-27 18:06
@SergioViteri , The issue is related to your instance, something is missing, check taxes on the product.
Maye be if you give me an access to your pos, I can check for you.

Thanks

**Comment by SergioViteri** [comment] 2015-10-28 08:30
@AdilHoumadi  What kind of access do you need? Can I send you an email or chat?

**Comment by AdilHoumadi** [comment] 2015-10-28 08:49
@SergioViteri, you can send me an email,
You can check my github profile.

**Comment by AdilHoumadi** [comment] 2015-10-28 17:56
@SergioViteri, @debaetsr, we can close this issue ?

**Comment by SergioViteri** [comment] 2015-10-28 18:00
@AdilHoumadi @debaetsr  Yes, finally upgrading Odoo resolved the issue. Thank you very much for your help!

**Closed as completed** 2015-11-28 10:42 UTC
